### ISSUE TITLE
TypeError: cannot read property 'writetext' of undefined

### ISSUE THREAD

**Issue by vmail** [hc-oss/react-web-share#13]
This error occurs when trying share via clipboard and forced into fallback mode (http://localhost:3000) in Chrome and stock browser. Works fine on PC

TypeError: cannot read property 'writetext' of undefined

**Comment by harshzalavadiya** [comment]
HI @vmail,

I'm not able to understand your issue, can you provide following details to diagnose issue properly?

browser w/ version: 
domain you are trying on:

**Comment by harshzalavadiya** [comment]
closing since no description provided, if it's still happening then please open another issue with sandbox
