### ISSUE TITLE
Add instagram

### ISSUE THREAD

**Issue by henriquesaias** [hc-oss/react-web-share#16]
Hey, great package thank you for making this available! 

I see instagram isn't one of the available sharing options though, do you think it's simple to add it? I need ig sharing in my platform, let me know if you plan on doing that soon or if I need to switch to another sharing tool. 

Best regards

**Comment by harshzalavadiya** [comment]
@henriquesaias AFAIK Instagram does not have direct share link API like facebook/other platforms since it's primary goal is to share images not link, if there is please let me know, I think I can remove LinkedIn 😂
