### ISSUE TITLE
Not working on mobile share

### ISSUE THREAD

**Issue by JeffersonBrito** [hc-oss/react-web-share#18]
It doesn't open share for mobile and even with desktop share, it keeps me an error (TypeError: cannot read property 'writetext' of undefined), all this in localhost...

**Comment by harshzalavadiya** [comment]
@JeffersonBrito can you provide an example or reporduction, since I'm able to trigger native and non-native just fine

**Comment by harshzalavadiya** [comment]
closing due to no response
