### ISSUE TITLE
Copy to Clipboard Not Working on Android

### ISSUE THREAD

**Issue by mattlockyer** [hc-oss/react-web-share#20]
Given the atrocious cross browser support:
https://caniuse.com/?search=clipboard

You might want to include something like:
https://www.npmjs.com/package/copy-to-clipboard

**Comment by harshzalavadiya** [comment]
@mattlockyer sorry, looks like this issue got buried in my notifications somewhere

I think it's been a long time and looks like support for this has improved a lot
I would like to avoid adding any additional dependency at this point but can be looked back

closing this for now
