### ISSUE TITLE
not closing the popup on click of outer overlay or else not working if i click on any social media icon to share detail 

### ISSUE THREAD

**Issue by komalharmale** [hc-oss/react-web-share#25]
Working properly for mobile view but not working on Desktop
 <RWebShare
                  data={{
                 text: "Like humans, flamingos make friends for life",
          url: "https://on.natgeo.com/2zHaNup",
          title: "Flamingos",
                  }}
                  onClick={() => console.log('shared successfully!')}
                  className={classes.divRight}
                  style={{
                    cursor: 'pointer',
                  }}>
                  <ShareIcon style={{ color: '#171717', fontSize: '18px' }} />
                </RWebShare>

**Comment by harshzalavadiya** [comment]
@komalharmale please provide reproducable sandbox with steps if this is still happening in v2.0.0 closing this for now
