### ISSUE TITLE
window.navigator.share is support in desktop 

### ISSUE THREAD

**Issue by Surojd** [hc-oss/react-web-share#28]
![image](https://user-images.githubusercontent.com/10323306/161732519-297b82fe-47db-42e0-87e1-d94c72398dab.png)

how to fix this.

**Comment by harshzalavadiya** [comment]
This is what called native share, this component works as polyfill where it isn't supported, but I guess if you want react component to be permanant, might be possible in future

**Comment by Surojd** [comment]
### We need to first show sites then native share for desktop
![image](https://user-images.githubusercontent.com/10323306/161993193-a55ab61c-b376-47c2-8fa3-92a219f97491.png)

**Comment by harshzalavadiya** [comment]
@Surojd It should only one of them not both because where native share fails it uses non-native share dialouge

**Comment by harshzalavadiya** [comment]
closing this feature is available in v2.0.0
